import Foundation

/// Represents a generated short-form video script section.
public struct ScriptSection: Codable, Identifiable, Hashable, Sendable {
    public var id: UUID
    public var timeRange: String // e.g. "0:00 - 0:03"
    public var sectionType: SectionType
    public var spokenText: String
    public var visualCue: String
    public var audioCue: String?
    
    public enum SectionType: String, Codable, CaseIterable, Sendable {
        case hook = "Hook (0-3s)"
        case patternInterrupt = "Pattern Interrupt"
        case body = "Core Value"
        case callToAction = "Call to Action"
    }

    public init(
        id: UUID = UUID(),
        timeRange: String,
        sectionType: SectionType,
        spokenText: String,
        visualCue: String,
        audioCue: String? = nil
    ) {
        self.id = id
        self.timeRange = timeRange
        self.sectionType = sectionType
        self.spokenText = spokenText
        self.visualCue = visualCue
        self.audioCue = audioCue
    }
}

/// Represents a full short-form script generated by ScriptFlip.
public struct Script: Codable, Identifiable, Hashable, Sendable {
    public var id: UUID
    public var title: String
    public var hookDurationSeconds: Int
    public var estimatedTotalDurationSeconds: Int
    public var style: ScriptStyle
    public var targetPlatform: TargetPlatform
    public var sections: [ScriptSection]
    public var viralityScore: Int // 1 to 100
    public var keyTakeaway: String
    
    // Convenience properties for Edge Function output format
    public var hook: String {
        sections.first(where: { $0.sectionType == .hook })?.spokenText ?? ""
    }
    public var body: String {
        sections.first(where: { $0.sectionType == .body })?.spokenText ?? ""
    }
    public var visualCue: String {
        sections.first(where: { $0.sectionType == .hook })?.visualCue ?? ""
    }
    public var cta: String {
        sections.first(where: { $0.sectionType == .callToAction })?.spokenText ?? ""
    }
    
    public enum TargetPlatform: String, Codable, CaseIterable, Identifiable, Sendable {
        case universal = "Universal (TikTok, Reels, Shorts)"
        case tikTok = "TikTok"
        case reels = "Instagram Reels"
        case shorts = "YouTube Shorts"
        
        public var id: String { rawValue }
        
        public var iconName: String {
            switch self {
            case .universal: return "sparkles.rectangle.stack.fill"
            case .tikTok: return "play.square.stack.fill"
            case .reels: return "camera.metering.matrix"
            case .shorts: return "play.tv.fill"
            }
        }
    }

    public init(
        id: UUID = UUID(),
        title: String,
        hookDurationSeconds: Int = 3,
        estimatedTotalDurationSeconds: Int = 30,
        style: ScriptStyle,
        targetPlatform: TargetPlatform = .universal,
        sections: [ScriptSection],
        viralityScore: Int = 94,
        keyTakeaway: String
    ) {
        self.id = id
        self.title = title
        self.hookDurationSeconds = hookDurationSeconds
        self.estimatedTotalDurationSeconds = estimatedTotalDurationSeconds
        self.style = style
        self.targetPlatform = targetPlatform
        self.sections = sections
        self.viralityScore = viralityScore
        self.keyTakeaway = keyTakeaway
    }
    
    /// Initialize full `Script` model from Supabase Edge Function DTO (`hook`, `body`, `visualCue`, `cta`)
    public init(dto: GeneratedScriptDTO, index: Int = 1, style: ScriptStyle = .casual) {
        self.id = UUID()
        self.title = "Universal Script: \(style.rawValue) Angle"
        self.hookDurationSeconds = 3
        self.estimatedTotalDurationSeconds = 30
        self.style = style
        self.targetPlatform = .universal
        
        self.sections = [
            ScriptSection(
                timeRange: "0:00 - 0:03",
                sectionType: .hook,
                spokenText: dto.hook,
                visualCue: dto.visualCue,
                audioCue: "High energy audio punch"
            ),
            ScriptSection(
                timeRange: "0:03 - 0:25",
                sectionType: .body,
                spokenText: dto.body,
                visualCue: "Dynamic camera cuts and text overlays"
            ),
            ScriptSection(
                timeRange: "0:25 - 0:30",
                sectionType: .callToAction,
                spokenText: dto.cta,
                visualCue: "Screen banner with follow / save prompt"
            )
        ]
        
        self.viralityScore = 94 + (index % 5)
        self.keyTakeaway = "Universal 3-second hook & high-retention pacing engineered for TikTok, Reels, and Shorts algorithms."
    }
    
    /// Full combined text suitable for teleprompter display.
    public var fullSpokenText: String {
        sections.map { "[\($0.sectionType.rawValue)]\n\($0.spokenText)" }.joined(separator: "\n\n")
    }
}
